version : '3'
services:
  php:
    build: ./php
    image: basisdata:latest
    container_name: php
    hostname: "php"
    volumes:
      - ./src_old:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on: 
      - mysql_db

  mysql_db:
    image: mariadb:10.2
    container_name: mysql_db
    restart: unless-stopped
    tty: true
    ports:
      - "43306:3306"
    volumes:
      - ./database/data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: Djoni!!
      MYSQL_PASSWORD: Djony
      MYSQL_ROOT_PASSWORD: Djony
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: nginx
    hostname: "nginx"
    ports:
      - "90:80"
    volumes:
      - ./src_old:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php